// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhAbfwEIgx-cnexjl24nTwVl6vWbrlRQQ',
    appId: '1:951172482218:android:c738d054ceaede21917cd3',
    messagingSenderId: '951172482218',
    projectId: 'communicationapp-4f8f5',
    storageBucket: 'communicationapp-4f8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptodbF4qccHVNj9x-QhvwG7rFVQMzGok',
    appId: '1:951172482218:ios:b60d4735b4844290917cd3',
    messagingSenderId: '951172482218',
    projectId: 'communicationapp-4f8f5',
    storageBucket: 'communicationapp-4f8f5.appspot.com',
    androidClientId: '951172482218-pouspkuvdro2vj359jjrh2futnqhnnau.apps.googleusercontent.com',
    iosClientId: '951172482218-37uplsi4qg2ug7mvvgv10nkpk4tqbl07.apps.googleusercontent.com',
    iosBundleId: 'com.example.communicationapp',
  );
}
